version: '3.9'

services:
  pythonapp_dev:
    container_name: pythonapp_dev
    image: pythonapp_dev
    build: .
    ports:
      - "80:80"
      - "10001:10001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - FLASK_ENV=development
      - DEBUGGER=True
      - FLASK_APP=api
      - CACHE_TYPE=redis
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379
      - CACHE_REDIS_DB=0
      - CACHE_REDIS_URL=redis://redis:6379/0
      - CACHE_DEFAULT_TIMEOUT=500
    depends_on:
      - db
      - redis

  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"


volumes:
  pgdata: {}